"""add credit_balance_checks to users

Revision ID: 56423a01890a
Revises: aefe194681aa
Create Date: 2026-04-24 13:33:45.719359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56423a01890a'
down_revision: Union[str, None] = 'aefe194681aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credit_balance_checks', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credit_balance_checks')
    # ### end Alembic commands ###
