"""drop api_keys.tier

Revision ID: 782a0d5c8b8a
Revises: 56423a01890a
Create Date: 2026-04-24 15:23:38.026974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782a0d5c8b8a'
down_revision: Union[str, None] = '56423a01890a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'tier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('tier', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
